# Generated by Django 5.2.4 on 2025-07-10 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('Time Based', 'Time-Based'), ('Lead Status', 'Lead Status')], max_length=50)),
                ('trigger_value', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('Send Email', 'Send Email'), ('Add to Campaign', 'Add to Campaign')], max_length=50)),
                ('target_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign')),
            ],
        ),
    ]
