# Generated by Django 5.2.4 on 2025-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('Time-based', 'Time-based'), ('Lead Status', 'Lead Status')], max_length=50),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_value',
            field=models.CharField(help_text="e.g. 'Qualified' or '2025-07-20'", max_length=100),
        ),
    ]
